// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ProvideraddproductTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void provideraddproduct() {
    driver.get("http://localhost:8000/provider/login");
    driver.manage().window().setSize(new Dimension(1853, 1053));
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("dias@ua.pt");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("pass");
    driver.findElement(By.cssSelector(".flex-c-m")).click();
    driver.findElement(By.linkText("Add Product")).click();
    driver.findElement(By.id("name")).click();
    driver.findElement(By.id("name")).sendKeys("Batman Mug");
    driver.findElement(By.id("price")).click();
    driver.findElement(By.id("price")).sendKeys("23.3");
    driver.findElement(By.id("image")).click();
    driver.findElement(By.id("image")).sendKeys("https://images-na.ssl-images-amazon.com/images/I/41lEIkSXJyL._AC_.jpg");
    driver.findElement(By.id("quantity")).click();
    driver.findElement(By.id("quantity")).sendKeys("1");
    driver.findElement(By.id("description")).click();
    driver.findElement(By.id("description")).sendKeys("batman mug");
    driver.findElement(By.cssSelector(".flex-c-m")).click();
  }
}
